---

- name: MEDIUM | UBTU-22-271010 | PATCH | Ubuntu 22.04 LTS must enable the graphical user logon banner to display the Standard Mandatory DOD Notice and Consent Banner before granting local access to the system via a graphical user logon.
  when:
    - ubtu22stig_271010
    - ubtu22stig_gui
  tags:
    - UBTU-22-271010
    - CAT2
    - CCI-000048
    - SRG-OS-000023-GPOS-00006
    - SV-260535r958390_rule
    - V-260535
    - NIST800-53R4_AC-8
    - gnome
  community.general.ini_file:
    path: /etc/gdm3/greeter.dconf-defaults
    section: 'org/gnome/login-screen'
    option: banner-message-enable
    value: 'true'
    mode: 'go-wx'
  notify:
    - Update_dconf
    - Restart_gdm3

- name: MEDIUM | UBTU-22-271015 | PATCH | Ubuntu 22.04 LTS must display the Standard Mandatory DOD Notice and Consent Banner before granting local access to the system via a graphical user logon.
  when:
    - ubtu22stig_271015
    - ubtu22stig_gui
  tags:
    - UBTU-22-271015
    - CAT2
    - CCI-000048
    - SRG-OS-000023-GPOS-00006
    - SV-260536r958390_rule
    - V-260536
    - NIST800-53R4_AC-8
    - gnome
  community.general.ini_file:
    path: /etc/gdm3/greeter.dconf-defaults
    section: 'org/gnome/login-screen'
    option: banner-message-text
    value: "{{ ubtu22stig_logon_banner | join('\n') }}"
    mode: 'go-wx'
  notify:
    - Update_dconf
    - Restart_gdm3

- name: MEDIUM | UBTU-22-271020 | PATCH | Ubuntu 22.04 LTS must retain a user's session lock until that user reestablishes access using established identification and authentication procedures.
  when:
    - ubtu22stig_271020
    - ubtu22stig_gui
  tags:
    - UBTU-22-271020
    - CAT2
    - CCI-000056
    - SRG-OS-000028-GPOS-00009
    - SV-260537r1069101_rule
    - V-260537
    - NIST800-53R4_AC-11
    - gnome
  community.general.ini_file:
    path: /etc/dconf/db/local.d/00-screensaver
    section: org/gnome/desktop/screensaver
    option: lock-enabled
    value: true
    mode: 'u-x,go-wx'
  notify: Update_dconf

- name: MEDIUM | UBTU-22-271025 | PATCH | Ubuntu 22.04 LTS must initiate a graphical session lock after 15 minutes of inactivity.
  when:
    - ubtu22stig_271025
    - ubtu22stig_gui
  tags:
    - UBTU-22-271025
    - CAT2
    - CCI-000057
    - SRG-OS-000029-GPOS-00010
    - SV-260538r1069119_rule
    - V-260538
    - NIST800-53R4_AC-11
    - gnome
  community.general.ini_file:
    path: /etc/dconf/db/local.d/00-screensaver
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: 'u-x,go-wx'
  notify: Update_dconf
  loop:
    - { section: org/gnome/desktop/screensaver, option: lock-enabled, value: true }
    - { section: org/gnome/desktop/screensaver, option: lock-delay, value: 0 }
    - { section: org/gnome/desktop/session, option: idle-delay, value: "{{ ubtu22stig_screen_lock_delay }}" }
